### ISSUE TITLE
Without CUDA

### ISSUE THREAD

**Issue by LalicJ** [bowang-lab/DeepVelo#6]
Hi, sorry to bother you. I was unable to install CUDA for CPU acceleration due to linux system limitations. Is there any way to run DeepVelo without using CPU acceleration? Any help would be greatly appreciated.

**Comment by subercui** [comment]
Hi @LalicJ Thank you for the question! The package is supposed to support running with CPU only. Could you try:

1. simply run `pip install deepvelo` as shown here https://github.com/bowang-lab/DeepVelo#installation .
2. Follow one of the notebooks to run on your data, for example, this one https://github.com/bowang-lab/DeepVelo/blob/main/examples/figure2.ipynb 
3. During the config settings, like this cell in the notebook
![image](https://github.com/bowang-lab/DeepVelo/assets/11674033/f7d76a23-3af1-48ec-a22e-b2c8efb27352)
    Set to use CPU only by
    ```
    configs = {
        "n_gpu": 0,
        # followed by other configs
    }
    ```

Please let me know if this works for you

**Comment by LalicJ** [comment]
Thanks for your reply! 
Set to use CPU only by
configs = {
    "n_gpu": 0,
    # followed by other configs
}
It works for me.
![image](https://github.com/bowang-lab/DeepVelo/assets/120431995/61527a44-b7a9-4bba-af20-15cbd1cddeeb)
