### ISSUE TITLE
cannot get environment solved (dgl)

### ISSUE THREAD

**Issue by MishalAshraf** [bowang-lab/DeepVelo#7]
Hello, 

I am trying to get the dependencies resolved to test out deepvelo. the issue I am having is that running "pip install deepvelo" installs dgl==1.1.2. as suggested in #5 , this leads to an issue with dgl.contrib. when installing an older version in the range suggested there (<0.8, >0.4.3, i picked 0.7.2). I had to pull the file directly as it did not work with conda or pip for me. doing this still results in an error "no module named dgl".

Any idea how i can get this working?

**Comment by MishalAshraf** [comment]
hello. putting this here for documentation purposes mostly. start with a fresh older python version and install the dependencies 1 by 1. worked for me.

**Comment by subercui** [comment]
Hi @MishalAshraf , thank you so much for the notice! Yes, we previously tested and developed the package in python 3.7
